name: Build Ghidra Allegrex

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: [ '10.1.5', '10.1.4', '10.1.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@0.0.6
        with:
          version: ${{ matrix.ghidra }}
      - name: Build Extension
        run: |
          chmod +x gradlew
          ./gradlew ghidraInstallThenPackage
          unzip ./build/dist/Allegrex.zip -d upload
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: upload
          name: Allegrex-Ghidra-${{ matrix.ghidra }}
          if-no-files-found: error
